# Generated by Django 3.2.8 on 2021-10-07 17:12

import datetime
from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=20, verbose_name='Genus')),
                ('species', models.CharField(max_length=30, verbose_name='Species')),
                ('strain_name', models.CharField(max_length=20, verbose_name='Strain')),
                ('access_number', models.CharField(max_length=10, verbose_name='Ceparium Number')),
                ('collection_date', models.DateField(default=datetime.datetime.now, verbose_name='Collection Date')),
                ('reactivation_date', models.DateField(verbose_name='Reactivation Date')),
                ('collection_place', models.CharField(max_length=50, verbose_name='Collection Place')),
                ('collection_point', djgeojson.fields.PointField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Strain',
                'verbose_name_plural': 'Strains',
                'db_table': 'strain',
                'ordering': ['genus'],
            },
        ),
    ]
