# Generated by Django 3.2.8 on 2021-10-07 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Genus',
                'verbose_name_plural': 'Genuses',
                'db_table': 'genus',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='strain',
            options={'ordering': ['species'], 'verbose_name': 'Strain', 'verbose_name_plural': 'Strains'},
        ),
        migrations.RemoveField(
            model_name='strain',
            name='genus',
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.genus')),
            ],
            options={
                'verbose_name': 'Species',
                'verbose_name_plural': 'Species',
                'db_table': 'species',
                'ordering': ['genus'],
            },
        ),
        migrations.AlterField(
            model_name='strain',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.species'),
        ),
    ]
