# Generated by Django 3.2.8 on 2021-10-09 14:41

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211007_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='genus',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', verbose_name='URL Slug'),
        ),
    ]
