# Generated by Django 3.2.8 on 2021-10-11 15:10

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_genus_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name'], 'verbose_name': 'Species', 'verbose_name_plural': 'Species'},
        ),
        migrations.AlterModelOptions(
            name='strain',
            options={'ordering': ['strain_name'], 'verbose_name': 'Strain', 'verbose_name_plural': 'Strains'},
        ),
        migrations.AddField(
            model_name='species',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name'),
        ),
        migrations.AddField(
            model_name='strain',
            name='identified_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Identified by'),
        ),
        migrations.AddField(
            model_name='strain',
            name='isolated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Isolated by'),
        ),
        migrations.AddField(
            model_name='strain',
            name='photo',
            field=models.ImageField(blank=True, default='core/static/ceparium/images/no-img.jpg', upload_to='core/static/ceparium/images/strains/'),
        ),
        migrations.AddField(
            model_name='strain',
            name='preparation',
            field=models.TextField(blank=True, null=True, verbose_name='Preparation'),
        ),
        migrations.AddField(
            model_name='strain',
            name='taxon_rank',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Taxonomic Rank'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='strain',
            name='access_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Ceparium Number'),
        ),
        migrations.AlterField(
            model_name='strain',
            name='strain_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Strain'),
        ),
    ]
