# Generated by Django 3.2.8 on 2021-10-11 20:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211011_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='collection_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
