# Generated by Django 3.2.8 on 2021-10-11 21:10

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_strain_collection_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='strain_name'),
        ),
    ]
