# Generated by Django 3.2.8 on 2021-10-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_strain_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='photo',
            field=models.ImageField(blank=True, default='static/ceparium/images/no-img.jpg', upload_to='static/ceparium/images/strains/'),
        ),
    ]
